#!/bin/sh

bspc monitor -d 1 2 3 4 5

bspc config top_padding 58
bspc config bottom_padding 0
bspc config window_gap 16
bspc config border_width 5
bspc config normal_border_color "#27292d"
bspc config active_border_color "#88a3e8"
bspc config focused_border_color "#88a3e8"
bspc config presel_feedback_color "#eaecf0"

feh --bg-fill /home/ilya/.dotfiles/assets/wallpaper2.jpg &
/home/ilya/.config/polybar/launch.sh &
